// <auto-generated />
using Group5_DBApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group5_DBApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Group5_DBApp.Models.Product", b =>
                {
                    b.Property<decimal>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProdId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProdId = 1m,
                            Price = 59.99m,
                            ProdName = "Wilson Evolution Indoor Basketball"
                        },
                        new
                        {
                            ProdId = 2m,
                            Price = 29.99m,
                            ProdName = "Spalding NBA Street Outdoor Basketball"
                        },
                        new
                        {
                            ProdId = 3m,
                            Price = 89.99m,
                            ProdName = "Nike Elite Championship Basketball"
                        },
                        new
                        {
                            ProdId = 4m,
                            Price = 39.99m,
                            ProdName = "Under Armour 495 Indoor/Outdoor Basketball"
                        },
                        new
                        {
                            ProdId = 5m,
                            Price = 44.99m,
                            ProdName = "Molten BGG Composite Basketball"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
